#!/usr/bin/env python
"""
Downloads stock data of all symbols in company_names.csv
"""
import argparse
from fastquant.data.stocks.pse import update_pse_data_cache

parser = argparse.ArgumentParser(
    description="update pse stock data cache"
)
parser.add_argument("--start_date", type=str, help="date in YYYY-MM-DD (default=2010-01-01)", default="2010-01-01")
args = parser.parse_args()
update_pse_data_cache(start_date=args.start_date, verbose=True)
